version: '2.1'

services:
  nginx:
    # front for the API, so we can set Access-Control-Allow-Origin (for swagger-ui)
    image: nginx
    ports:
      - 8886:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - api
  notebook:
    image: jupyter/minimal-notebook
    env_file: .env
    environment:
      NB_UID: ${NB_UID:-1000}
    # https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook#docker-options
    # root will drop privileges
    user: root
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - ./:/home/jovyan/work
  api:
    image: felix/jupyter-kernel-gateway
    build: .
    command: --KernelGatewayApp.seed_uri=/home/jovyan/work/api_intro.ipynb --port=8889
    env_file: .env
    environment:
      NB_UID: ${NB_UID:-1000}
    # https://github.com/jupyter/docker-stacks/tree/master/scipy-notebook#docker-options
    # root will drop privileges
    user: root
    ports:
      - 127.0.0.1:8889:8889
    volumes:
      - ./:/home/jovyan/work
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      # if you change this, be sure to change it in nginx.conf too!
      - 127.0.0.1:8887:8080

